[tool.poetry]
name = "log4shell"
version = "0.1.0"
description = ""
authors = ["shoxxdj <remi.martin-de-abia@advens.fr>"]

[tool.poetry.dependencies]
python = "^3.10"
colorama = "^0.4.4"
argparse = "^1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
log4shell="log4shell.exploit:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
